main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

contact:
    path:     /contact
    defaults: { _controller: MainBundle:Default:contact }
    requirements:
            _method:  GET|POST

search:
    path:     /search
    defaults: { _controller: MainBundle:Search:searchTreat }

a_propos:
    path:     /a_propos
    defaults: { _controller: MainBundle:Default:a_propos }

estimation:
    path:     /estimation
    defaults: { _controller: MainBundle:Default:estimationetape1 }

estimation2:
    path:     /estimation2
    defaults: { _controller: MainBundle:Default:estimationetape2 }

estimation3:
    path:     /estimation3
    defaults: { _controller: MainBundle:Default:estimationetape3 }

audiovisuel_detail:
    path:     /audiovisuel_detail
    defaults: { _controller: MainBundle:Default:audiovisuel_detail }

contact:
    path:     /contact
    defaults: { _controller: MainBundle:Default:contact }

equipe:
    path:     /equipe
    defaults: { _controller: MainBundle:Default:equipe }

graphic_detail:
    path:     /graphic_detail
    defaults: { _controller: MainBundle:Default:graphic_detail }

index:
    path:     /index
    defaults: { _controller: MainBundle:Default:index }

projets:
    path:     /projets
    defaults: { _controller: MainBundle:Default:projets }

searchProjets:
    pattern: /searchProjets
    defaults: { _controller: MainBundle:Default:searchprojets }

services:
    path:     /services
    defaults: { _controller: MainBundle:Default:services }


web_detail:
    path:     /web_detail
    defaults: { _controller: MainBundle:Default:web_detail }

graphic_detail:
    path:     /graphic_detail
    defaults: { _controller: MainBundle:Default:graphic_detail }

materiel_detail:
    path:     /materiel_detail
    defaults: { _controller: MainBundle:Default:materiel_detail }

reseau_detail:
    path:     /reseau_detail
    defaults: { _controller: MainBundle:Default:reseau_detail }

audiovisuel_detail:
    path:     /audiovisuel_detail
    defaults: { _controller: MainBundle:Default:audiovisuel_detail }

projet_detail:
    path:     /{id}/projet_detail
    defaults: { _controller: MainBundle:Default:projet_detail }
