main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

contact:
    path:     /contact
    defaults: { _controller: MainBundle:Default:contact }
    requirements:
            _method:  GET|POST

search:
    path:     /search
    defaults: { _controller: MainBundle:Search:searchTreat }
